---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: master
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        files: \.(scss)$
        additional_dependencies:
          - "stylelint@13.7.2"
          - "stylelint-config-standard@20.0.0"
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: master
    hooks:
      - id: markdownlint
        entry: markdownlint
        language: node
        types: [markdown]
        minimum_pre_commit_version: 0.15.0
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, main]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: htmlhint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.14.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@7.14.0
        files: \.(ts)$
        types: [file]
  - repo: git@github.com:a-ibs/pre-commit-mirrors-jsonlint
    rev: master
    hooks:
      - id: jsonlint
